require('dotenv').config();
const pool = require('./config/db');

async function seed() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS dtc_codes (
      code                  VARCHAR(10) PRIMARY KEY,
      short_description     TEXT NOT NULL,
      description           TEXT NOT NULL,
      possible_causes       TEXT[] NOT NULL DEFAULT '{}',
      symptoms              TEXT[] NOT NULL DEFAULT '{}',
      severity              VARCHAR(10) NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
      urgency               VARCHAR(50),
      repairs               JSONB NOT NULL DEFAULT '[]',
      oem_cost_min          INTEGER,
      oem_cost_max          INTEGER,
      aftermarket_cost_min  INTEGER,
      aftermarket_cost_max  INTEGER,
      labor_hours_min       NUMERIC(4,1),
      labor_hours_max       NUMERIC(4,1),
      diy_difficulty        VARCHAR(10) CHECK (diy_difficulty IN ('easy', 'moderate', 'hard'))
    )
  `);
  console.log('Table ready');

  const codes = [
    {
      code: 'P0300',
      short_description: 'Random / Multiple Cylinder Misfire',
      description: 'The engine is misfiring in one or more cylinders at random. This can cause rough running and damage the catalytic converter if left unaddressed.',
      possible_causes: ['Worn or fouled spark plugs', 'Faulty ignition coils', 'Clogged or leaking fuel injectors', 'Low compression (worn engine)', 'Vacuum leaks'],
      symptoms: ['Rough idle or shaking', 'Engine hesitation or stumbling', 'Check engine light flashing (severe misfire)', 'Poor acceleration and fuel economy'],
      severity: 'high',
      urgency: 'Within 1 week',
      repairs: [
        { fix: 'Replace spark plugs', oem: '$100–$250', aftermarket: '$40–$100' },
        { fix: 'Replace ignition coil(s)', oem: '$150–$350', aftermarket: '$60–$150' },
        { fix: 'Clean / replace fuel injectors', oem: '$200–$500', aftermarket: '$80–$250' },
      ],
      oem_cost_min: 100, oem_cost_max: 500,
      aftermarket_cost_min: 40, aftermarket_cost_max: 250,
      labor_hours_min: 1.0, labor_hours_max: 2.5,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0301',
      short_description: 'Cylinder 1 Misfire Detected',
      description: 'Cylinder 1 is misfiring, meaning it is not firing correctly or at all. Persistent misfires on a single cylinder can damage the catalytic converter and indicate a failing ignition or fuel component.',
      possible_causes: ['Faulty spark plug on cylinder 1', 'Bad ignition coil on cylinder 1', 'Leaking or clogged fuel injector', 'Low compression in cylinder 1', 'Intake manifold gasket leak'],
      symptoms: ['Rough idle with noticeable shaking', 'Check engine light on or flashing', 'Loss of power on acceleration', 'Increased fuel consumption'],
      severity: 'high',
      urgency: 'Within 1 week',
      repairs: [
        { fix: 'Replace spark plug (cyl 1)', oem: '$30–$80', aftermarket: '$15–$40' },
        { fix: 'Replace ignition coil (cyl 1)', oem: '$100–$250', aftermarket: '$50–$120' },
        { fix: 'Replace fuel injector (cyl 1)', oem: '$150–$350', aftermarket: '$60–$180' },
      ],
      oem_cost_min: 30, oem_cost_max: 350,
      aftermarket_cost_min: 15, aftermarket_cost_max: 180,
      labor_hours_min: 0.5, labor_hours_max: 1.5,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0420',
      short_description: 'Catalytic Converter Efficiency Low',
      description: 'Your catalytic converter is not reducing emissions as effectively as it should. This is often triggered when the converter wears out or is damaged by oil or coolant contamination.',
      possible_causes: ['Worn or damaged catalytic converter', 'Engine oil or coolant burning (contaminating the cat)', 'Faulty upstream or downstream O2 sensor', 'Exhaust leaks before the catalytic converter'],
      symptoms: ['Check engine light on', 'Possible sulfur / rotten egg smell from exhaust', 'Slightly reduced fuel economy', 'May fail emissions test'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Replace catalytic converter', oem: '$800–$1,500', aftermarket: '$200–$600' },
        { fix: 'Replace O2 sensor(s)', oem: '$150–$300', aftermarket: '$80–$150' },
        { fix: 'Repair exhaust leak', oem: '$100–$300', aftermarket: '$50–$150' },
      ],
      oem_cost_min: 800, oem_cost_max: 1500,
      aftermarket_cost_min: 200, aftermarket_cost_max: 600,
      labor_hours_min: 1.5, labor_hours_max: 3.0,
      diy_difficulty: 'moderate',
    },
    {
      code: 'P0430',
      short_description: 'Catalyst System Efficiency Low (Bank 2)',
      description: 'The catalytic converter on Bank 2 (the side of the engine without cylinder 1) is operating below efficiency threshold. Same cause profile as P0420 but on the opposite bank.',
      possible_causes: ['Worn catalytic converter on Bank 2', 'Faulty downstream O2 sensor (Bank 2)', 'Engine oil or coolant contaminating the cat', 'Exhaust leak upstream of converter'],
      symptoms: ['Check engine light on', 'Sulfur smell from exhaust', 'Reduced fuel economy', 'Failed emissions test'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Replace catalytic converter (Bank 2)', oem: '$800–$1,500', aftermarket: '$200–$600' },
        { fix: 'Replace O2 sensor (Bank 2)', oem: '$150–$300', aftermarket: '$80–$150' },
      ],
      oem_cost_min: 800, oem_cost_max: 1500,
      aftermarket_cost_min: 200, aftermarket_cost_max: 600,
      labor_hours_min: 1.5, labor_hours_max: 3.0,
      diy_difficulty: 'moderate',
    },
    {
      code: 'P0171',
      short_description: 'Fuel System Too Lean (Bank 1)',
      description: 'The engine is running with too much air and not enough fuel on Bank 1. Over time a lean condition can cause engine damage and should be diagnosed promptly.',
      possible_causes: ['Vacuum leak (cracked hose or intake manifold gasket)', 'Dirty or faulty mass airflow (MAF) sensor', 'Weak fuel pump or clogged fuel filter', 'Faulty oxygen sensor', 'Clogged fuel injectors'],
      symptoms: ['Check engine light on', 'Rough idle', 'Hesitation on acceleration', 'Reduced fuel economy'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Fix vacuum leak', oem: '$100–$400', aftermarket: '$30–$150' },
        { fix: 'Clean / replace MAF sensor', oem: '$200–$400', aftermarket: '$50–$150' },
        { fix: 'Replace fuel pump', oem: '$400–$800', aftermarket: '$150–$400' },
      ],
      oem_cost_min: 100, oem_cost_max: 800,
      aftermarket_cost_min: 30, aftermarket_cost_max: 400,
      labor_hours_min: 1.0, labor_hours_max: 3.0,
      diy_difficulty: 'moderate',
    },
    {
      code: 'P0174',
      short_description: 'Fuel System Too Lean (Bank 2)',
      description: 'The engine is running lean on Bank 2. When both P0171 and P0174 are present together, a common intake leak or a failing MAF sensor is usually the cause.',
      possible_causes: ['Vacuum or intake air leak', 'Faulty MAF sensor', 'Clogged fuel injectors on Bank 2', 'Weak fuel pressure', 'Faulty oxygen sensor (Bank 2)'],
      symptoms: ['Check engine light on', 'Rough or unstable idle', 'Hesitation under load', 'Poor fuel economy'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Fix vacuum / intake leak', oem: '$100–$400', aftermarket: '$30–$150' },
        { fix: 'Replace MAF sensor', oem: '$200–$400', aftermarket: '$50–$150' },
        { fix: 'Clean fuel injectors', oem: '$150–$350', aftermarket: '$60–$180' },
      ],
      oem_cost_min: 100, oem_cost_max: 800,
      aftermarket_cost_min: 30, aftermarket_cost_max: 400,
      labor_hours_min: 1.0, labor_hours_max: 3.0,
      diy_difficulty: 'moderate',
    },
    {
      code: 'P0128',
      short_description: 'Coolant Temp Below Thermostat Temp',
      description: 'Your engine is not reaching its normal operating temperature. Usually caused by a stuck-open thermostat and affects fuel economy and heater performance.',
      possible_causes: ['Thermostat stuck open', 'Faulty coolant temperature sensor', 'Low coolant level'],
      symptoms: ['Temperature gauge stays low', 'Poor heater output in cold weather', 'Reduced fuel economy', 'Check engine light on'],
      severity: 'low',
      urgency: 'Within 1 month',
      repairs: [
        { fix: 'Replace thermostat', oem: '$150–$350', aftermarket: '$50–$150' },
        { fix: 'Replace coolant temp sensor', oem: '$100–$200', aftermarket: '$30–$80' },
      ],
      oem_cost_min: 100, oem_cost_max: 350,
      aftermarket_cost_min: 30, aftermarket_cost_max: 150,
      labor_hours_min: 0.5, labor_hours_max: 1.5,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0442',
      short_description: 'EVAP System Leak Detected (Small)',
      description: 'A small leak has been detected in the evaporative emission control system. Start by checking your gas cap — it is the most common and cheapest fix.',
      possible_causes: ['Loose or damaged gas cap', 'Cracked EVAP hose or line', 'Faulty purge valve or vent valve', 'Damaged charcoal canister'],
      symptoms: ['Check engine light on', 'Faint fuel smell near the vehicle', 'May fail emissions test'],
      severity: 'low',
      urgency: 'Check gas cap first',
      repairs: [
        { fix: 'Replace gas cap', oem: '$20–$50', aftermarket: '$10–$25' },
        { fix: 'Replace EVAP hose / line', oem: '$100–$300', aftermarket: '$40–$120' },
        { fix: 'Replace purge or vent valve', oem: '$150–$350', aftermarket: '$50–$150' },
      ],
      oem_cost_min: 20, oem_cost_max: 350,
      aftermarket_cost_min: 10, aftermarket_cost_max: 150,
      labor_hours_min: 0.5, labor_hours_max: 2.0,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0455',
      short_description: 'EVAP System Large Leak Detected',
      description: 'A large leak has been detected in the evaporative emission system. More urgent than P0442; common causes include a missing or cracked gas cap or a split EVAP hose.',
      possible_causes: ['Missing, loose, or cracked gas cap', 'Large crack in EVAP line or hose', 'Damaged charcoal canister', 'Faulty vent or purge solenoid'],
      symptoms: ['Check engine light on', 'Strong fuel odor', 'May fail emissions test'],
      severity: 'low',
      urgency: 'Within 1 month',
      repairs: [
        { fix: 'Replace gas cap', oem: '$20–$50', aftermarket: '$10–$25' },
        { fix: 'Replace EVAP hose / canister', oem: '$200–$500', aftermarket: '$80–$250' },
        { fix: 'Replace purge / vent valve', oem: '$150–$350', aftermarket: '$50–$150' },
      ],
      oem_cost_min: 20, oem_cost_max: 500,
      aftermarket_cost_min: 10, aftermarket_cost_max: 250,
      labor_hours_min: 0.5, labor_hours_max: 2.0,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0446',
      short_description: 'EVAP Vent Control Circuit Malfunction',
      description: 'The EVAP canister vent valve circuit is not functioning correctly. This prevents the system from venting properly and can trap fuel vapors.',
      possible_causes: ['Faulty EVAP vent solenoid', 'Blocked or clogged vent line', 'Wiring harness damage to vent solenoid', 'PCM failure (rare)'],
      symptoms: ['Check engine light on', 'Fuel smell', 'Difficulty filling gas tank (overpressure)'],
      severity: 'low',
      urgency: 'Within 1 month',
      repairs: [
        { fix: 'Replace EVAP vent solenoid', oem: '$100–$250', aftermarket: '$40–$100' },
        { fix: 'Inspect / repair vent line', oem: '$80–$200', aftermarket: '$30–$80' },
      ],
      oem_cost_min: 80, oem_cost_max: 250,
      aftermarket_cost_min: 30, aftermarket_cost_max: 100,
      labor_hours_min: 0.5, labor_hours_max: 1.5,
      diy_difficulty: 'moderate',
    },
    {
      code: 'P0401',
      short_description: 'EGR Flow Insufficient Detected',
      description: 'The exhaust gas recirculation (EGR) system is not flowing enough exhaust back into the intake. A clogged EGR valve or passages is the most common cause.',
      possible_causes: ['Clogged or stuck EGR valve', 'Blocked EGR passages or tubes', 'Faulty EGR pressure or differential pressure sensor', 'Vacuum leak to EGR valve'],
      symptoms: ['Check engine light on', 'Engine knocking or pinging under load', 'Rough idle', 'Failed emissions test'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Clean / replace EGR valve', oem: '$200–$500', aftermarket: '$60–$200' },
        { fix: 'Clean EGR passages', oem: '$100–$300', aftermarket: '$40–$120' },
        { fix: 'Replace EGR pressure sensor', oem: '$80–$200', aftermarket: '$30–$90' },
      ],
      oem_cost_min: 80, oem_cost_max: 500,
      aftermarket_cost_min: 30, aftermarket_cost_max: 200,
      labor_hours_min: 1.0, labor_hours_max: 2.5,
      diy_difficulty: 'moderate',
    },
    {
      code: 'P0011',
      short_description: 'Camshaft Timing Over-Advanced (Bank 1)',
      description: 'The camshaft on Bank 1 is more advanced than the ECU commanded. Usually caused by oil flow issues to the variable valve timing (VVT) system.',
      possible_causes: ['Low engine oil level or dirty oil', 'Faulty camshaft actuator (OCV/OCS)', 'Timing chain stretch or wear', 'Faulty camshaft position sensor'],
      symptoms: ['Check engine light on', 'Rough idle', 'Engine rattle on cold start', 'Reduced power'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Oil change (first step)', oem: '$60–$120', aftermarket: '$40–$80' },
        { fix: 'Replace camshaft actuator', oem: '$200–$600', aftermarket: '$80–$250' },
        { fix: 'Replace timing chain', oem: '$500–$1,500', aftermarket: '$200–$700' },
      ],
      oem_cost_min: 500, oem_cost_max: 1500,
      aftermarket_cost_min: 200, aftermarket_cost_max: 700,
      labor_hours_min: 3.0, labor_hours_max: 8.0,
      diy_difficulty: 'hard',
    },
    {
      code: 'P0340',
      short_description: 'Camshaft Position Sensor Circuit (Bank 1)',
      description: 'The ECU is not receiving a valid signal from the camshaft position sensor on Bank 1. This can prevent the engine from starting or cause stalling.',
      possible_causes: ['Faulty camshaft position sensor', 'Damaged wiring or connector to sensor', 'Reluctor wheel damage or debris', 'PCM failure (rare)'],
      symptoms: ['Engine may not start', 'Stalling while driving', 'Check engine light on', 'Rough running'],
      severity: 'high',
      urgency: 'Within 1 week',
      repairs: [
        { fix: 'Replace camshaft position sensor', oem: '$100–$300', aftermarket: '$30–$100' },
        { fix: 'Repair sensor wiring / connector', oem: '$80–$250', aftermarket: '$30–$100' },
      ],
      oem_cost_min: 80, oem_cost_max: 300,
      aftermarket_cost_min: 30, aftermarket_cost_max: 100,
      labor_hours_min: 0.5, labor_hours_max: 1.5,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0507',
      short_description: 'Idle Air Control System RPM High',
      description: 'The engine idle speed is higher than the target RPM set by the ECU. Often caused by a vacuum leak or a dirty throttle body allowing extra air into the engine.',
      possible_causes: ['Vacuum leak', 'Dirty or faulty idle air control (IAC) valve', 'Dirty throttle body', 'Faulty throttle position sensor'],
      symptoms: ['High idle (above ~1,000 RPM when warm)', 'Fluctuating idle', 'Check engine light on'],
      severity: 'low',
      urgency: 'Within 1 month',
      repairs: [
        { fix: 'Clean throttle body', oem: '$80–$200', aftermarket: '$30–$80' },
        { fix: 'Replace IAC valve', oem: '$100–$300', aftermarket: '$40–$120' },
        { fix: 'Fix vacuum leak', oem: '$80–$300', aftermarket: '$30–$120' },
      ],
      oem_cost_min: 80, oem_cost_max: 300,
      aftermarket_cost_min: 30, aftermarket_cost_max: 120,
      labor_hours_min: 0.5, labor_hours_max: 1.5,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0562',
      short_description: 'System Voltage Low',
      description: 'The ECU has detected that system voltage is below the expected threshold. This often points to a failing battery or alternator.',
      possible_causes: ['Weak or failing battery', 'Faulty alternator', 'Corroded battery terminals', 'Parasitic battery drain', 'Faulty voltage regulator'],
      symptoms: ['Dim headlights or interior lights', 'Slow engine cranking', 'Battery warning light', 'Check engine light on', 'Electrical glitches'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Replace battery', oem: '$150–$300', aftermarket: '$80–$180' },
        { fix: 'Replace alternator', oem: '$300–$700', aftermarket: '$120–$350' },
        { fix: 'Clean battery terminals', oem: '$30–$60', aftermarket: '$10–$30' },
      ],
      oem_cost_min: 150, oem_cost_max: 700,
      aftermarket_cost_min: 80, aftermarket_cost_max: 350,
      labor_hours_min: 0.5, labor_hours_max: 2.0,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0500',
      short_description: 'Vehicle Speed Sensor Malfunction',
      description: 'The vehicle speed sensor (VSS) is sending an incorrect or no signal to the ECU. This can affect speedometer accuracy, transmission shifting, and ABS.',
      possible_causes: ['Faulty vehicle speed sensor', 'Damaged wiring or connector', 'Faulty ABS sensor (on some vehicles)', 'Differential or transmission issue'],
      symptoms: ['Speedometer inoperative or erratic', 'Harsh or erratic transmission shifts', 'ABS or traction control light on', 'Check engine light on'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Replace vehicle speed sensor', oem: '$80–$250', aftermarket: '$30–$100' },
        { fix: 'Repair VSS wiring / connector', oem: '$80–$200', aftermarket: '$30–$80' },
      ],
      oem_cost_min: 80, oem_cost_max: 250,
      aftermarket_cost_min: 30, aftermarket_cost_max: 100,
      labor_hours_min: 0.5, labor_hours_max: 2.0,
      diy_difficulty: 'moderate',
    },
    {
      code: 'P0113',
      short_description: 'Intake Air Temp Sensor Circuit High',
      description: 'The intake air temperature (IAT) sensor is reporting an abnormally high voltage, suggesting the sensor or its circuit has an open condition.',
      possible_causes: ['Faulty IAT sensor', 'Open circuit in IAT sensor wiring', 'Poor connector contact', 'Faulty PCM (rare)'],
      symptoms: ['Check engine light on', 'Possible rough idle or hesitation', 'Hard starting in cold weather', 'Rich or lean running condition'],
      severity: 'low',
      urgency: 'Within 1 month',
      repairs: [
        { fix: 'Replace IAT sensor', oem: '$50–$150', aftermarket: '$15–$60' },
        { fix: 'Repair sensor wiring', oem: '$60–$150', aftermarket: '$20–$60' },
      ],
      oem_cost_min: 50, oem_cost_max: 150,
      aftermarket_cost_min: 15, aftermarket_cost_max: 60,
      labor_hours_min: 0.5, labor_hours_max: 1.0,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0102',
      short_description: 'Mass Air Flow Circuit Low Input',
      description: 'The MAF sensor is outputting a signal lower than expected, causing the ECU to under-estimate airflow and run the engine improperly.',
      possible_causes: ['Dirty or contaminated MAF sensor', 'Air leak between MAF and throttle body', 'Faulty MAF sensor', 'Damaged MAF wiring or connector'],
      symptoms: ['Check engine light on', 'Rough idle', 'Hesitation or stumbling on acceleration', 'Poor fuel economy', 'Black smoke from exhaust'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Clean MAF sensor', oem: '$30–$80', aftermarket: '$10–$30' },
        { fix: 'Replace MAF sensor', oem: '$200–$400', aftermarket: '$50–$150' },
        { fix: 'Repair intake air leak', oem: '$60–$200', aftermarket: '$20–$80' },
      ],
      oem_cost_min: 30, oem_cost_max: 400,
      aftermarket_cost_min: 10, aftermarket_cost_max: 150,
      labor_hours_min: 0.5, labor_hours_max: 1.0,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0131',
      short_description: 'O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)',
      description: 'The upstream oxygen sensor on Bank 1 is reading a consistently low voltage, indicating the sensor may be faulty or the engine is running very lean.',
      possible_causes: ['Faulty upstream O2 sensor', 'Exhaust leak near the sensor', 'Lean fuel condition (vacuum leak, low fuel pressure)', 'Damaged O2 sensor wiring'],
      symptoms: ['Check engine light on', 'Poor fuel economy', 'Rough idle', 'Failed emissions test'],
      severity: 'medium',
      urgency: 'Within 2 weeks',
      repairs: [
        { fix: 'Replace upstream O2 sensor', oem: '$150–$300', aftermarket: '$40–$120' },
        { fix: 'Repair exhaust leak', oem: '$100–$300', aftermarket: '$40–$120' },
        { fix: 'Repair O2 sensor wiring', oem: '$80–$200', aftermarket: '$30–$80' },
      ],
      oem_cost_min: 80, oem_cost_max: 300,
      aftermarket_cost_min: 30, aftermarket_cost_max: 120,
      labor_hours_min: 0.5, labor_hours_max: 1.5,
      diy_difficulty: 'easy',
    },
    {
      code: 'P0135',
      short_description: 'O2 Sensor Heater Circuit (Bank 1, Sensor 1)',
      description: 'The heater element inside the upstream oxygen sensor on Bank 1 is not working correctly. A cold O2 sensor provides inaccurate readings, affecting fuel trim.',
      possible_causes: ['Failed O2 sensor heater element', 'Blown fuse for O2 sensor heater', 'Damaged wiring or connector', 'PCM output failure (rare)'],
      symptoms: ['Check engine light on', 'Slightly poor fuel economy until engine warms up', 'May cause rough cold start'],
      severity: 'low',
      urgency: 'Within 1 month',
      repairs: [
        { fix: 'Replace upstream O2 sensor', oem: '$150–$300', aftermarket: '$40–$120' },
        { fix: 'Check / replace O2 heater fuse', oem: '$5–$20', aftermarket: '$5–$15' },
        { fix: 'Repair sensor wiring', oem: '$80–$200', aftermarket: '$30–$80' },
      ],
      oem_cost_min: 5, oem_cost_max: 300,
      aftermarket_cost_min: 5, aftermarket_cost_max: 120,
      labor_hours_min: 0.5, labor_hours_max: 1.5,
      diy_difficulty: 'easy',
    },
  ];

  for (const dtc of codes) {
    await pool.query(
      `INSERT INTO dtc_codes (
         code, short_description, description, possible_causes, symptoms,
         severity, urgency, repairs,
         oem_cost_min, oem_cost_max, aftermarket_cost_min, aftermarket_cost_max,
         labor_hours_min, labor_hours_max, diy_difficulty
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
       ON CONFLICT (code) DO UPDATE SET
         short_description    = EXCLUDED.short_description,
         description          = EXCLUDED.description,
         possible_causes      = EXCLUDED.possible_causes,
         symptoms             = EXCLUDED.symptoms,
         severity             = EXCLUDED.severity,
         urgency              = EXCLUDED.urgency,
         repairs              = EXCLUDED.repairs,
         oem_cost_min         = EXCLUDED.oem_cost_min,
         oem_cost_max         = EXCLUDED.oem_cost_max,
         aftermarket_cost_min = EXCLUDED.aftermarket_cost_min,
         aftermarket_cost_max = EXCLUDED.aftermarket_cost_max,
         labor_hours_min      = EXCLUDED.labor_hours_min,
         labor_hours_max      = EXCLUDED.labor_hours_max,
         diy_difficulty       = EXCLUDED.diy_difficulty`,
      [
        dtc.code, dtc.short_description, dtc.description, dtc.possible_causes, dtc.symptoms,
        dtc.severity, dtc.urgency, JSON.stringify(dtc.repairs),
        dtc.oem_cost_min, dtc.oem_cost_max, dtc.aftermarket_cost_min, dtc.aftermarket_cost_max,
        dtc.labor_hours_min, dtc.labor_hours_max, dtc.diy_difficulty,
      ]
    );
    console.log(`  seeded ${dtc.code}`);
  }

  console.log(`Done — ${codes.length} DTC codes seeded.`);
  await pool.end();
}

seed().catch(err => { console.error(err); process.exit(1); });
